### ISSUE TITLE
Major Console Error

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#103]
I've been getting this in my console plugin while using movecraft with spigot 1.8.3. Any ideas on what it means? it sounds bad.

**Comment by msummers123** [comment]
What was the error you were getting?

**Comment by Pocketkid2** [comment]
Woops, sorry. Forgot to add logs
http://pastebin.com/NKrTjdgy

**Comment by msummers123** [comment]
Yes, I thought this might be the case. What you are seeing is actually a Spigot error. You can read about it here:
https://hub.spigotmc.org/jira/browse/SPIGOT-611

I am working on a workaround, since it seems unlikely Spigot will fix it.

**Comment by msummers123** [comment]
Fixed in the latest version
