### ISSUE TITLE
Crafts don't respond

### ISSUE THREAD

**Issue by 2spoopy4meh** [msummers123/Movecraft-3#105]
Movecraft Version: V 3.1.X73

Spigot Version: Occurred on both 1.8.3 Build 373 and 1.8 Build 27

No errors on startup. No errors in the logs/console or messages to the player (Messages such as:You successfully piloted this craft) when attempting to interact (right-click) with a properly setup "Airship" sign ("Airship" being the name of the craft). First line: Airship

All necessary permissions are given. 

Craft config: http://pastebin.com/KxSTWNsP

What am I doing wrong, or what is going on?

**Comment by msummers123** [comment]
So you get no message at all when you right click an airship sign?
Sounds like either the plugin isn't actually loading, or the .craft file wasn't found, or something else is going on. 

First off, lets verify basic functionality of the plugin. Make a sign that says simply:
[helm]
including the brackets. Right click that sign. It should turn into a wheel icon looking thing. That almost always works, unless movecraft isn't even loaded.

Assuming that works, check on startup in the server console for how many .craft files it things it found. It always assumes one, so we are hoping for a number greater than 1.

**Comment by 2spoopy4meh** [comment]
Movecraft does in fact load, and all 8 of my crafts load. Here is a latest log from just a few minutes ago. Ctrl + f and movecraft to find the thingy. http://pastebin.com/isrutL9n

Rotation signs do still make the change after interaction when the bug is occurring. I tested this yesterday on Spigot build 27, and I just had someone test it while using Spigot build 373.

**Comment by msummers123** [comment]
I don't know what to tell you. It's working fine for me. Could you screenshot the command sign you are trying to use?

**Comment by 2spoopy4meh** [comment]
http://imgur.com/LnFHe9k,MjQiMb8#0 Attempted with both a capital "A" and a lowercase. Although, it wasn't case sensitive in the past, sooo...? 

Could there be a conflict with another plugin? Here is the list of plugins I use. http://pastebin.com/RaiLK3aj 
Worldguard is at 5.9 and worldedit is at 5.6.3. Protocol Lib is on a dev build from March 15th (if that even matters). All of the other plugins are on the latest versions (Last checked March 21st).

I don't know if any of this information is of use to you, but it seems like you have no idea what is going on, so the more info, the better?

**Comment by msummers123** [comment]
I've read from other users that apparently some builds of spigot are having issues with signs. Here is what they said:

" I found the solution, you were correct. It was with the jars. I downloaded a new jar from http://tcpr.ca/spigot . BUT make sure to download the 18 MB version from march 7th. I have tried the build tools for 1.8.3 but it encounters an error in compiling. I hope that helps with your current problem.﻿"

**Comment by mwkaicz** [comment]
You should try to remove plugins which uses sings one by one.  I can confirm that problem isn't in Essentials and SignURL

**Comment by dawaffle54** [comment]
I have had the same problems and I looked throughout the server log and saw that it was disabling Vaul Compatibility And Vault Compatibility, And I Found That Once Installing The Plugins Its Disabling (Vault, WorldEdit WorldGuard) It for some reason worked

**Comment by 2spoopy4meh** [comment]
Some of my current plugins don't work on that build of spigot. I did try removing plugins that deal with signs, and it didn't work. Dawaffle, that solution doesn't seem like a very good one as I already have vault, worldguard, worldedit, and factions (which are basically a few of the "optional" dependencies for this plugin). I do appreciate you trying to help though. Hopefully somebody has a solution to this other than switching to a spigot build I can't use. Every other plugin that deals with binding events to signs works properly on the latest spigot builds (essentials, kingkits, tutorialsigns, signurls, zvp, areashop, chestshop, randomtp, stats, ect.), so why doesn't this one on the latest spigot builds? At this point, adding a command or some sort of temporary alternative would be more than alright with me. Also, like I said before in the original post, it didn't work on spigot build 27, which came long before build 373. I didn't think of that before testing it on the build you told me to test it on.

**Comment by msummers123** [comment]
I have tested it with 1.8.3 spigot with a build that was the newest as of 4/1/2015, and I can confirm it works. I have a series of steps for you:
First, try using the command:
/pilot airship
While standing on the craft. Watch your server console for errors, if airship is not a valid type it recognized, it will give you a null pointer error.

If it succeeds, try:
/cruise north

If neither succeeds, delete your entire types directory (or, if you prefer, rename it to OldTypes). Then restart the server. Movecraft will recreate the types directory. Without modifying any .craft files, try the:
/pilot airship
command again.

**Comment by 2spoopy4meh** [comment]
Well, after 2 weeks, I still don't have it working. I'll give you a full log with responses from one of my moderators with proper permissions for the latest spigot build from build tools and X80 movecraft. Please look at the plugins I use and see if any interference could be caused by them. Do I need worldedit 6.0 and worldguard 6.0 in order to function properly? Is there like a problem between the factions version and this version of movecraft? There has go to be some sort of explanation for this. o_o

Log file: http://pastebin.com/TGp3yS95

Airship.craft file: http://pastebin.com/6mGCjEJu

config.yml file: http://pastebin.com/inMEMcEQ

**Comment by mwkaicz** [comment]
No, you don't need any else plugin. Factions shouldn't have any effect to Movecraft (but I not tested it)

In your init log I don't see any reason why it shouldn't works. I suppose that some plugin disabed click event on the sign. Could you please try it on clear server just with spigot and movecraft (absolutely supported plugins are at this time WE, WG, Vault and Cannons).

**Comment by 2spoopy4meh** [comment]
I will try to find someone with a test server to test out the plugin and add all the plugins I use 1 by 1 to figure out if a plugin is conflicting with movecraft, and to figure out what plugin it may be. After I do this, I will report what I find.

**Comment by 2spoopy4meh** [comment]
On a test server, when I added movecraft and ZombieVsPlayer into the plugins directory, the airships wouldn't work, but both plugins would load. So the problem is being caused by ZVP, but what part of ZVP is causing this error. Movecraft and ZVP are essential to gameplay on my server, and I hope you haz an answer for dis >.>

**Comment by mwkaicz** [comment]
I looked into code of ZvP, it looks like it detects owns signs from stored locations ... so maybe there was ZvP sign in some previous time on same position as you have now airship sign. BUT:
Problem must be in ZvP PlayerInteractListener (it stops right click event though sign isn't part of the ZvP) ZvP uses HIGH priority for capture click event and movecraft uses normal priority. So Movecraft can't detect any action and that's the reason why it doesn't say anything.

Try to contact ZvP author and request a fix.

**Comment by AlexMl** [comment]
Hi im the dev oft zvp. What you habe said seems right. I am going to look into it. I changed the eventpriority because other Plugins affected my game too.

**Comment by AlexMl** [comment]
I looked it up and i can not confirm what @mwkaicz  said. ZvP cancels the event only if the sign is part of the plugin. The priority affects only the moment and order of event processing.

**Comment by mwkaicz** [comment]
Ok, lets talk about that. 
Theoreticaly: What's happend when you create ZvP sign and then remove it via some plugin (f.e: WorldEdit) or just via explosion (I don't see in your any explosion event listener in your code) ... and then on the same location is placed another sign f.e. Movecraft sign "airship" 

Can your plugin detect that this new sign on same location as previous (which was saved with ZvP sign) isn't part of your plugin?  I didn't look too much deeper in your plugin but as I can see in PlayerInteractListener all what detect is only location and then you taking data from store in config ... there isn't any new sign content detection. And I think this should be one of cases when your plugin can block another sign, because (row 96):
```if (event.getAction() == Action.RIGHT_CLICK_BLOCK) {	// Player join per Sign
	    if (this.sm.isZVPSign(event.getClickedBlock().getLocation())) {
		if (this.sm.getType(event.getClickedBlock().getLocation()) == SignType.INTERACT_SIGN) {
```
... these 3 goes true if sign has same location and it was interact sign
```if (!GameManager.getManager().isInGame(eventPlayer)) {``` ... false 
and it's redirected to else: 
```
} else {
   event.setCancelled(true);
   eventPlayer.sendMessage(MessageManager.getMessage("game:already_in_game"));
   return;
}
 ```
... and now event is canceled just for same (undeleted) location 

This is just my opinion and I'll be grateful if you can refute it.

**Comment by AlexMl** [comment]
It is nice that you responded so fast. Thanks.

It's true that my plugin doesn't check on explosions or worldedit. But it will throw an exception if the sign is removed no matter how it was destroyed. If a sign is placed on that exact location it will override the content with previous information. And if you think about it, that is a really neat feature. For instance if you accidentally remove the block behind the sign or just think about a creeper in your lobby.

I don't know how Movecraft handles his signs. Maybe it overrides my overridden ones. 

I added a validation check anyways but i don't think this will fix the issue. I had tested it by myself but movecraft is crashing my server instantly. And besides that, my game works perfectly without movecraft so that is not a valid argument.

@2spoopy4meh Please check the new release 2.4.2: 
https://github.com/AlexMl/ZvP/releases/tag/ZvP-v2.4-4

**Comment by mwkaicz** [comment]
"But it will throw an exception if the sign is removed no matter how it was destroyed" 

where can I find this part of code? (just for interest)

**Comment by AlexMl** [comment]
I forgot to say that it will be thrown on reload. 
1. [The SignManager loads the signs from disk] (https://github.com/AlexMl/ZvP/blob/master/src/me/Aubli/ZvP/Sign/SignManager.java#L65)
2. [Constructor of InfoSign class:](https://github.com/AlexMl/ZvP/blob/master/src/me/Aubli/ZvP/Sign/InfoSign.java#L86)
```
 if (this.signLoc.getBlock().getState() instanceof Sign) {
	this.sign = (Sign) this.signLoc.getBlock().getState(); //cast sign (only when block is sign)
	update(); //Override content of the sign
 } else {
	throw new Exception("...");
 }
```

It was an craftbukkit error (Tick took too long: Forced shutdown) works on spigot

**Comment by mwkaicz** [comment]
Ok, I see, but this doesn't solves replaced signs too. 
Some servers are not restarted few weeks (but i suppose that when admin has problem, he will try it)

You should to use in each interaction same validation as you have in SignChangeEvent.
at least ```if (sign.getLine(0).equalsIgnoreCase("[zvp]")){```
 Only then you can be sure that you have really ZvP sign.

**Comment by AlexMl** [comment]
It will check it the way you just told. I changed it 2 hours ago.

We need to wait until he has tested it.

**Comment by 2spoopy4meh** [comment]
I just tested it, and it did not work. We must remember here that airships don't respond whatsoever when the ZvP plugin is added on a server with the plugins list provided in one of my comments above this one and on a clear test server. The command to pilot airships doesn't work along with the sign, so signs are not the problem here. I don't know much about code, but I think looking at the events that allow for the activation of a craft and how ZvP could interfere with those events would be helpful. =P

**Comment by mwkaicz** [comment]
I'll try to debug it tomorrow when I'll have some free time.

**Comment by mwkaicz** [comment]
First view (debug both plugins and spigot from sources):

Crap, this is worse than I thought. When ZvP is active, Movecraft AsyncManager.processAlgorithmQueue() never gets new tasks. ZvP must somehow prevent Movecrafts AsyncManager (extends BukkitRunnable) to add new tasks or remove them. ... I'll do more tests today afternoon.

**Comment by AlexMl** [comment]
ZvP does cancel some tasks that may cause some errors.

**Comment by mwkaicz** [comment]
not some tasks, all of them! This is the part in your plugin when/why Movecraft stops reacting:
```
public void stopGames() {
	for (Arena a : getArenas()) {
	    a.stop();
	}
	Bukkit.getScheduler().cancelAllTasks();
    }
``` 
you stop everything include our AsyncManager ... this is main problem why Movecraft don't want to do anything when your plugin is running ... because he can't .

**Comment by AlexMl** [comment]
Glad you found something. I will fix this today.

**Comment by AlexMl** [comment]
I fixed it and it should solve the problem. 

https://github.com/AlexMl/ZvP/releases/tag/ZvP-v2.4-5

**Comment by mwkaicz** [comment]
Ok, I go to test it.

**Comment by mwkaicz** [comment]
Yes, now it's correct :) Both plugins works.Thx, it's nice to work with someone in the same time zone :)

@2spoopy4meh: let's try it.

**Comment by AlexMl** [comment]
Thanks too. Timezones can be tricky. :+1:

**Comment by 2spoopy4meh** [comment]
Looks like the movecraft plugin responds when some of it's commands are run! Issue now seems to be resolved! Thank you to all who provided support during this issue.
