### ISSUE TITLE
Bad Bug

### ISSUE THREAD

**Issue by TylerS1066** [msummers123/Movecraft-3#106]
Crafts will move through blocks after a explosion.

For example once the torpedo blows up once it continues on through and blocks destroying them but not exploding.

And skiffs when they sink they explode in the ground and then sink their way through bedrock.

This also creates alot of lag, so much that it fried the processor on one of the player's computers

**Comment by msummers123** [comment]
Yeah, the core issue is that air is not colliding anymore. I will work on this ASAP.

**Comment by msummers123** [comment]
This is fixed in the latest build
