### ISSUE TITLE
Are you sure we fixed this?

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#112]
http://pastebin.com/G7HvQq0i

**Comment by msummers123** [comment]
No, this can't be fixed. It is a more serious bug in Spigot, I reported it as https://hub.spigotmc.org/jira/browse/SPIGOT-610
This only affects comparators, the other bug affected any other block with tile data like containers. I eventually found a semi-workaround which was to change it to a sign, then to air. That prevents chunk corruption, but spits out thousands of these error messages on the console.

However, I considered that better than causing chunk corruption. Unlike the other issue, this does not have any solution I am aware of

**Comment by Pocketkid2** [comment]
Darnit!

**Comment by msummers123** [comment]
I'm going to close this for now, as it isn't a movecraft error, and I don't know of any workaround other than what I've already done.
