### ISSUE TITLE
Torpedoes wont explode?

### ISSUE THREAD

**Issue by mjcrafter100** [msummers123/Movecraft-3#114]
Whenever I launch a torp. it flies normally, but wont explode, I checked the type config, and the movecraft config, and it should be working fine. And it seems like it does, everything pans out right, 'craft can not move' message. 'piloted craft' message, even explosion effects, just no explosion.
it is DEF. not world guard, I checked that.
the problem occurred today, after working flawlessly for a while.
Any idea why?

**Comment by msummers123** [comment]
You may have a different plugin other than worldguard that is blocking explosions, or if this is underwater use, spill protection may be blocking the explosion. If you have a world with a non-standard waterline, IE: a water line above 62, spill protection will trigger above 62 and prevent damage to prevent spilling from tnt cannons. This does not affect above-water use, or underwater use below 62.

If that is the issue, just disable spill protection (disablespillprotection: true in config.yml)

**Comment by mjcrafter100** [comment]
Well, TNT works, so I dont think it is a protection issue.
i disabled spill protection, and that STILL didnt work.
could it be that movecraft is conflicting with my server version? (Because of the plugin update)

**Comment by msummers123** [comment]
Is this underwater use?

**Comment by mjcrafter100** [comment]
No

**Comment by msummers123** [comment]
Ok, then it definitely isn't spill protection. 

TNT is a different event than the kind of explosion caused by torpedo. Torpedoes cause a generic minecraft explosion event. Worldguard calls this "other-explosion". Other protection plugins may call it something else. 

Also make sure this isn't near your server spawn.

**Comment by mjcrafter100** [comment]
Ok, in the region, I have other-explosions set to allow. and it is nowhere near the spawn, plus up until today, it was working

**Comment by mjcrafter100** [comment]
here is the config for the torpedo:
name: LaunchTorpedo
maxSize: 45
minSize: 1
allowedBlocks: 
    - 173

forbiddenBlocks:
    - 7

canCruise: true
cruiseOnPilot: true
cruiseSkipBlocks: 0
canFly: false
minHeightLimit: 65
maxHeightLimit: 65
collisionExplosion: 6.0
explodeOnCrash: 2.0
sinkSpeed: 5.0
smokeOnSink: 0
keepMovingOnSink: true
moveEntities: false
speed: 7.0
tryNudge: false
sinkPercent: 99.0
flyblocks:
    173:
        - 50.0
        - 100.0

**Comment by msummers123** [comment]
Rename your types folder as typesold and restart the server so it is recreated. That will eliminate the craft file as a possible cause. 

If that does not fix it, we need to run the server with a clean install. Where the only plugins installed are movecraft and worldedit.

**Comment by mjcrafter100** [comment]
So disable all plugins but movecraft and world edit?

**Comment by msummers123** [comment]
Correct, and also rename your movecraft/types folder to typesold so it will be recreated

**Comment by mjcrafter100** [comment]
Ok, I will test it once my server starts to work again, the hosting company got hacked, so I may not be able to give you the results till tomorrow.

**Comment by msummers123** [comment]
Any update on this? I would like to close some tickets

**Comment by mjcrafter100** [comment]
Fixed. sorry for the late reply
