### ISSUE TITLE
Movecraft wont respond??

### ISSUE THREAD

**Issue by mjcrafter100** [msummers123/Movecraft-3#116]
So I installed the newest update for movecraft, and nothing responds. I am resetting my movecraft folder to see if that helps, but  if that doesnt work,  I will just be using the Feb. 23rd version

**Comment by mjcrafter100** [comment]
Yeap, doesnt work....

**Comment by mwkaicz** [comment]
Some error in the log file?

**Comment by mjcrafter100** [comment]
nope, checked for that.
the only reason I want the update is because I thought it would fix my torpedo problem

**Comment by msummers123** [comment]
It turns out the new version requires worldedit, even if you disable that integration. I will get it fixed when I can. Until then you may have to install worldedit.

**Comment by mjcrafter100** [comment]
I have WE installed, IDK why it wont work :/

**Comment by msummers123** [comment]
I assume this is working now? I'd like to close this ticket
