### ISSUE TITLE
Large airships descending

### ISSUE THREAD

**Issue by impressiveinfantry** [msummers123/Movecraft-3#118]
Large ships keep descending for what reason i dont know. airships work just fine but big and mega airships plummet to the ground like rocks attached to gas bags. i have no idea why this is happening. i could use some explanations

**Comment by msummers123** [comment]
You are probably seeing the maxheightaboveground limit in effect. Most craft types are limited to 100 blocks over the terrain below them. The Airship should have been as well, but its possible the limitation was changed, or its also possible the midpoint of the airship just happened to be over ground that was not too far distant. (It only checks the midpoint to avoid lag). 

The reason maxheightaboveground is important is that lag from moving crafts comes largely from lighting updates within Minecraft itself. The more open space below an airship, the more lighting updates, the more lag.

Where this is often a problem is in sky island maps. On those maps, its probably best to simply remove maxheightaboveground. Unfortunately, it also means Movecraft will lag considerably more on such a server than it would on a standard world.
