### ISSUE TITLE
Paperspigot improvement (not a bug or request)

### ISSUE THREAD

**Issue by impressiveinfantry** [msummers123/Movecraft-3#126]
just happened to come across a new type of spigot a few days ago. the only information i got from this new branch was that paperspigot fixes some glitches and bugs from normal spigot and some gameplay mechanics improvements as well. it greatly improves movecrafts capabilities, allowing for large ships to move at fast speeds without causing that much lag. also the glitches and bugs of movecraft seem radically reduced. i used to have quite a few bugs playing on normal spigot, but paperspigot seems to fix all of them. for those who are having movecraft issues related to spigot, i recommend using this improved version(although it updates much less compared to normal spigot). for those of you who are interested in paperspigot: here is the link: http://tcpr.ca/paperspigot i hope this gets some interest because my movecraft experience greatly improved with this version.

**Comment by mwkaicz** [comment]
Very well, I'll try it :)

**Comment by jflory7** [comment]
We're using PaperSpigot on our main survival server (no Movecraft), but I hadn't tried it yet on our next project server (uses Movecraft). I'll make sure to also report any results I find in testing.

**Comment by impressiveinfantry** [comment]
ill tell you what im able to turn and move the goliath with minimal difficulty on my server. i was not even able to pilot the goliath on normal spigot, let alone move it  and turn it with minimal error. my tests show remarkable improvements. there are very few bugs or glitches that happen in paperspigot compared to normal spigot.

**Comment by mwkaicz** [comment]
After some tests I can confirm that. At this moment I can overload cpu thread with 20k ship only on detection task. Translation is pretty much more smoother than with normal Spigot.

**Comment by msummers123** [comment]
This sounds very exciting to me and I would like to know more about it.

Although so far it seems the same for me. I'm running paperspigot 1.8.3 and spigot 1.8.3 and in both cases when I move a 17k airship about 50 blocks above the ground it starts by taking 1300 ms, and after a few moves it eventually goes down to about 800 ms. I am moving straight forward one block at a time.

This is the ship I am testing with:
http://www.planetminecraft.com/project/working-air-warship-shadow-of-the-deep-pirate-refit-2-submersible-battleship-with-heavy-tnt-cannon-turrets/

I added a debug: true setting to the config.yml so you can easily measure the time it took to update the map. You can get it from the beta build link here:
https://dl.dropboxusercontent.com/u/11164014/movecraft_beta.zip

This build also has several bug fixes, most notably with no more item duplication and items no longer falling off in some situations. Also it has all mwkaicz's improvements, like the custom WG flags.

**Comment by impressiveinfantry** [comment]
glad to know your finally back from your long vacation Mark :)

**Comment by mwkaicz** [comment]
@msummers123: God man, you fixed pistons, I bless you :)

**Comment by msummers123** [comment]
Any more info on this?

**Comment by mwkaicz** [comment]
No, I stopped to using pure Spigot :)
