### ISSUE TITLE
Wmd and torpedo not working

### ISSUE THREAD

**Issue by gravestristen** [msummers123/Movecraft-3#127]
We have the wmd and torpedo files on the server but they do not launch. when I tried to launch the wmd it had said that I had successfully piloted the craft but it did not move at all.

**Comment by mwkaicz** [comment]
Maybe you have deprecated craft files. Look in wmd.craft If there is cruiseOnPilot: true

**Comment by gravestristen** [comment]
That line is missing, I got the files directly from the wiki link on here.

**Comment by gravestristen** [comment]
name: WMD
maxSize: 20
minSize: 4
allowedBlocks: 
    - 156
    - 138
    - 57
    - 155

forbiddenBlocks:
    - 7

canCruise: true
cruiseSkipBlocks: 0
canFly: false
minHeightLimit: 65
maxHeightLimit: 65
collisionExplosion: 100.0
speed: 5.0
tryNudge: false
sinkPercent: 99.0
flyblocks:
    138:
        - 20.0
        - 100.0

**Comment by mwkaicz** [comment]
Ok, thats our mistake. In the past there wasn't this option and torpedo, rocket, wmd etc. must have Cruise: Off sign too. Now you don't need this sing, if you put there cruiseOnPilot: true ... so add this row and your problems will be gone :)

**Comment by gravestristen** [comment]
the wmd needs a cruise off sign for it to work?

**Comment by mwkaicz** [comment]
You have two options:
1) add ```cruiseOnPilot: true``` to the wmd.craft 
or
2) add ```Cruise: OFF``` sign
