### ISSUE TITLE
Some crafts wont burn fuel. 

### ISSUE THREAD

**Issue by mjcrafter100** [msummers123/Movecraft-3#134]
Checked config for issues, but my bigairship wont burn fuel. Its fuel burn rate is set to 4.0
I am going to test other airships.
Airskiffs seem to burn fuel.

**Comment by msummers123** [comment]
A common cause of this is a typo in the craft file. Basically it fails before it reads the fuelburnrate. Check for failures on server boot that talk about a craft file problem.

**Comment by mjcrafter100** [comment]
Ok, will look into it.
What are some common typos to look out for?

**Comment by mwkaicz** [comment]
maybe you have wrong spacing, unexpected chars or something else. Go row by row and compare it with another file which is correct.

**Comment by mjcrafter100** [comment]
When I looked at the file, it seemed good, I did get it from a download from baccas YT channel.
IDK if I changed it though.
I think Im going to re-download the folder, and compare them.

**Comment by msummers123** [comment]
A common problem is adding tabs to the file. I've done it myself a number of times. YAML format files don't like tabs for some reason.

**Comment by mjcrafter100** [comment]
Its fixed, turned out it was a small typo, had to scan the type file for a while.

**Comment by TylerS1066** [comment]
My solution to the tabbing issue is to use Notepad++ and set it to use 4 spaces instead of tabs
