### ISSUE TITLE
Ship broke on server shutdown

### ISSUE THREAD

**Issue by TylerS1066** [msummers123/Movecraft-3#139]
So I restarted bacca's beta survival server while Samcavan was cruising along on his ship.
his ship was torn to pieces and all chests and furnaces were cleared.  (I rebuilt his ship for him)

I saved the wreckage as SamBrokeShip.
Here's some pics:
![2015-06-07_11 56 44](https://cloud.githubusercontent.com/assets/7319776/8025022/c9a7eb9c-0d0d-11e5-8207-24ceaef86801.png)
![2015-06-07_11 56 50](https://cloud.githubusercontent.com/assets/7319776/8025024/c9a98024-0d0d-11e5-8faa-dfe8b21a0e5a.png)
![2015-06-07_11 56 56](https://cloud.githubusercontent.com/assets/7319776/8025025/c9aa6214-0d0d-11e5-89a7-05d15d79c536.png)
![2015-06-07_11 57 01](https://cloud.githubusercontent.com/assets/7319776/8025026/c9ab3662-0d0d-11e5-886d-fa3ed7b56662.png)
![2015-06-07_11 57 06](https://cloud.githubusercontent.com/assets/7319776/8025023/c9a81900-0d0d-11e5-8a05-31e53254a916.png)

**Comment by mwkaicz** [comment]
This is very interesting, as I know that's not first time, when you have this problem. I can understand when some part/chunk is missing, but these holes are weird. It looks like chunk corruption, I have never seen this on my server (since 2011).

**Comment by msummers123** [comment]
Yeah, I'm sure it was caused by the chunk being half saved when the server restarted. It probably crashed when it was trying to shut down, I have been seeing that alot. The only thing I can think of we can do is release all the ships before restarting.

Hopefully I can do something about the lag which is the underlying problem.

**Comment by TylerS1066** [comment]
It happened again, to about 5 ships this time.  One thing I noticed is that the ship slices lay right on chunk boundaries

**Comment by keough99** [comment]
maybe have a system in the plugin that detects a restart so then it releases all crafts?

**Comment by msummers123** [comment]
Not really something I can fix, sadly
