### ISSUE TITLE
Signs, Torches and doors "pop" off

### ISSUE THREAD

**Issue by TylerS1066** [msummers123/Movecraft-3#141]
So on both of bacca's servers, we have encountered an issue where signs, torches and doors randomly pop off of the block they were attached to.  This is so common that you can't even move 20 blocks without losing all your signs.

It does NOT affect all signs, torches and doors, just affects a majority of them within the ship, and it seems to follow a pattern.

Movecraft Version: 3.1.X82

**Comment by msummers123** [comment]
Should be fixed now. There are still some rare circumstances where things will pop off, but 99% of these should be fixed.
