### ISSUE TITLE
Ship rotation lava problems

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#143]
I was playing with your silver empire advanced carrier on my server, using a recent version of Movecraft. (I updated it yesterday morning) 

One of the fighters has lava on the sides for fire arrows, and when I rotated the lava spread weirdly. See the picture.

Rotating does look a bit weird. It appears to happen slower on large ships, kinda like the difference between regular WorldEdit and AsyncWorldEdit.
![movecraft-error-1](https://cloud.githubusercontent.com/assets/3046638/8264173/f6087880-1697-11e5-818d-7e5824cc56b2.png)

**Comment by TylerS1066** [comment]
This is a unexpected side effect of the new update, basically ships are moving in sections, instead of all at once.  This makes bigger ships slower and has had some unintended side effects, this is one of them that may or may not be fixed yet.

**Comment by Pocketkid2** [comment]
XD I suspected that much

**Comment by msummers123** [comment]
This should now be fixed
