### ISSUE TITLE
[Requested Feature] ChairsReloaded support?

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#144]
Could you add support in the plugin for the ChairsReloaded plugin? http://dev.bukkit.org/bukkit-plugins/chairsreloaded/

The way it would work would be, you can sit in a chair, and when you move a ship, the chair moves, and you move with it, and you stay sitting. Currently, when you move the ship, the chair moves, and you do, but you immediately stop sitting and are just standing inside the chair block. This would be a really amazing and fun addition, and I think it would be possible.

It looks like ChairsReloaded has an API: https://github.com/Shevchik/Chairs/tree/arrow/src/com/cnaude/chairs/api

**Comment by Pocketkid2** [comment]
I did some testing and Chairs itself may need some work or something to get this to work well, but i'd like to see what could be done

**Comment by Pocketkid2** [comment]
Maybe if a simple chairs support was added to the plugin itself? that would be really cool. Like you can sit in a chair if its part of a piloted craft, and then you would move and stay sitting with the chair

**Comment by msummers123** [comment]
No plans to implement this

**Comment by Pocketkid2** [comment]
Oh Cmon
