### ISSUE TITLE
Random Sinking

### ISSUE THREAD

**Issue by danielcbailey** [msummers123/Movecraft-3#145]
About a week ago I was testing a train concept, and after piloting it and attempting to move it, it randomly sunk. Here is what happened, I piloted the craft as an airship, and wanted to make it cruise, so I executed /cruise north, it didn't move at all for about 20 seconds, and then craft has taken too much damage. and it starts sinking. Not only is that weird but the wreck it left in the air, which never got removed with the rest of it, it never piloted some parts of the craft. Now this issue was brought back to my attention when a player with the user blockmonster200 was flying their ship in the survival server and it randomly sunk. I have a few screenshots from when the glitch happened to me.
![2015-06-26_07 40 22](https://cloud.githubusercontent.com/assets/9934819/8511963/7f601718-22fb-11e5-9af2-ff029e79a564.png)
![2015-06-26_07 40 34](https://cloud.githubusercontent.com/assets/9934819/8511964/80a6e372-22fb-11e5-9a8d-6235aad3a47f.png)
![2015-06-26_07 40 50](https://cloud.githubusercontent.com/assets/9934819/8511965/81cb5198-22fb-11e5-967b-dc6fa4887a7e.png)

**Comment by keough99** [comment]
i was there to see it happen

**Comment by msummers123** [comment]
I believe all random sinking behavior is now resolved.
