### ISSUE TITLE
Where to get "radar" and "beam me up" add ons?

### ISSUE THREAD

**Issue by mjcrafter100** [msummers123/Movecraft-3#153]
I saw them being used in the survival server, and wanted to know where to get them?
;
Thanks!

**Comment by TheRealBotcrusher** [comment]
Hey, beam is a separate plugin.
You should be able to find it through the group, or by searching movecraft
( second page)

**Comment by mjcrafter100** [comment]
I dont understand. Could you elaborate?

**Comment by TheRealBotcrusher** [comment]
Ok, well beam is a seperate plugin entirely. Tyler admin wrote it, search
it on git.

As for radar, you should be able to follow the "added contacts" comments

**Comment by mjcrafter100** [comment]
Ok, what about the "Radar"

**Comment by TheRealBotcrusher** [comment]
Radar is actually called contacts in the code.
You should be able to follow the comment trail in the git

**Comment by TylerS1066** [comment]
Yes I wrote beaming, later today I will be pushing out a update to it:
https://www.spigotmc.org/resources/beaming.8094/

**Comment by mjcrafter100** [comment]
Ok, about the "contact" since it is in a "dev" build of movecraft, and not released to bukkit forums, where can I find it? I looked everywhere O.o

**Comment by TheRealBotcrusher** [comment]
Erm... You are looking at the source code.
Jist compile it.

**Comment by TylerS1066** [comment]
Or download it from here:
https://dl.dropboxusercontent.com/u/11164014/movecraft_beta.zip

**Comment by mjcrafter100** [comment]
Thanks tyler!
