### ISSUE TITLE
Have a plane fly on a set path?

### ISSUE THREAD

**Issue by ColeSkory** [msummers123/Movecraft-3#155]
Is there a way to have a plane move on a set path? 
We want to have a unmanned "Bus plane' that will go on a set route to pick players us.
If this is not possible, can you think of a workaround for this with boundaries maybe?

Thanks! Have a wonderful day!
Cole

**Comment by TheRealBotcrusher** [comment]
https://www.youtube.com/watch?v=1w_rem0_fKY
Courtesy of snowleopard, in a skype message

**Comment by msummers123** [comment]
Greater support for truly scripted flight paths would be nice, and is on the todo list somewhere. But for now, the link provided is the only option.

**Comment by Pocketkid2** [comment]
It really shouldn't be hard to code a specialized virtual pilot into the plugin (think CBWrapper) that can execute simple scripts with simple move actions like TURN_LEFT, CRUISE_ON, WAIT, etc...
