### ISSUE TITLE
/contacts detection

### ISSUE THREAD

**Issue by keough99** [msummers123/Movecraft-3#157]
hello can someone tell me what to put into the .craft file for the detection system so i can get it working

**Comment by TylerS1066** [comment]
do you have the dev build?

**Comment by keough99** [comment]
Yes

**Comment by msummers123** [comment]
you need to put detectionMultiplier and underwaterDetectionMultiplier. For examples, see the example crafts here:
https://www.dropbox.com/s/9epcj386phjqa9f/MovecraftTypes.zip?dl=0
