### ISSUE TITLE
Download link.

### ISSUE THREAD

**Issue by 3767jack** [msummers123/Movecraft-3#163]
It does not really work. I pressed enter by mistake, sorry about that.
Anywho, the download link does not work for me. Is there a mirror I could use to download the 1.8 thing of it?

**Comment by msummers123** [comment]
Errr... are you looking for a place to download the most recent version of the plugin? I just recently updated this one:
http://www.planetminecraft.com/mod/movecraft-reloaded---loraxe42s-fork/

**Comment by 3767jack** [comment]
I fixed it. Nevermind. Thanks though!
