### ISSUE TITLE
Repair Signs saying "not enough material" when the materials are there

### ISSUE THREAD

**Issue by KevinC66** [msummers123/Movecraft-3#179]
I am having issues with my repair signs. The problem is that I have all the materials to repair my ship's damage in my chest, but it still says it doesn't have enough materials to repair the ship and I'm facing the right direction without any of my turrets turned. Does anyone know the solution to this problem? Thanks.

**Comment by msummers123** [comment]
Could you be more specific? What things did it say it was missing? What percentages? What is in the chest? Is it a trapped chest?

**Comment by KevinC66** [comment]
I destroyed a white wool block to test if it would repair. The repair was 0% and all my white wool was in a trapped chest and a regular chest.

**Comment by msummers123** [comment]
Let's be as specific as possible. Here is what I want you to do:
1 - pilot the craft
2 - left click the repair sign
3 - it should say "state saved". Does it?
4 - remove one block of wool
5 - right click the sign. What does it say? Please provide the entire text.

It would also be helpful if you can get me a copy of your server log file.

**Comment by KevinC66** [comment]
I think the materials have to be stored in a regular chest. It's all working now in a regular chest. Thanks for taking time and viewing my issue; I really appreciate it. Thanks.
