### ISSUE TITLE
How do I allow people to fly in certain region?

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [msummers123/Movecraft-3#181]
Title says it all. By enabling "Build", I allow players to place/ break blocks, and I don't want that.
If I don't allow to "Build", they can't fly.

**Comment by mwkaicz** [comment]
there is support for World Guard Custom Flags plugin 
in config:
WGCustomFlagsUseMoveFlag, WGCustomFlagsUsePilotFlag, WGCustomFlagsUseRotatetFlag, WGCustomFlagsUseSinkFlag

custom flags in WG:
movecraft-pilot, movecraft-move, movecraft-rotate and movecraft-sink

more details: 
http://www.planetminecraft.com/mod/movecraft-reloaded---loraxe42s-fork/ (Customization Features)
