### ISSUE TITLE
Can players be required as flight blocks.

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#183]
I posted this on the wrong movecraft GitHub. I am looking for the possibility to have players required as fly blocks for certain crafts. Or at least to make that a configurable option. For example, I have a ram Craft on my server. I would love to be able to make it only operate when more than one person is on it. So, for example. It would not move unless I had two players on the ram itself. I am not looking for user-specific signatures or anything, just general checks on a real players are on the craft.

**Comment by mwkaicz** [comment]
joining threads: https://github.com/AJCStriker/Movecraft-3/issues/163

I'll continue answer on previous, because there is more comments from you now.

**Comment by pistols12** [comment]
Ok ty
