### ISSUE TITLE
Sub crafts, that require a certain mother craft

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#185]
Hello all, I have a question regarding sub crafts and Crafts. I am looking to be able to make a working catapult, the only way I have found to do this is to make two separate crafts. One craft that acts as the catapults ammunition, and the Catapult craft itself. The only problem this creates, is that people can just use the ammunition by itself. They do not need the Catapult to fire it. I am wondering if I can make a craft, require another type of craft as its parent. For example my catapult ammunition would require the Catapult craft to work. Is this possible, is there anything I can do to help, and if it is possible when might it be gotten to. I know that's kind of a hard question to answer sometimes, but a general answer would be great.

**Comment by mwkaicz** [comment]
At this point, this option isn't possible without source code change. But after that, yes, because similar function is used in subcraft detection, but it will be slow, because after detection of subcraft, you will must make detection of parent which will be much bigger than catapult/balista. Are you sure, that this is best option? I can't imagine 20 or 50 craft-projectiles moving in same time. Do you know Cannons plugin?

**Comment by pistols12** [comment]
Ok, well atm people seem to be not doing too bad with it, but just wanted to see what, if any options were already existing to combat this. I just get all googly eyed when I imagine my self on s catapult flinging firepots into a village to set it aflame for nit paying weekly demands of Rome. LoL

**Comment by mwkaicz** [comment]
Same thing you can make with Cannons too (it's supported by Movecraft for some time) ... there is very customable config for projectiles and barrels (i know, looking on couple of bricks flying to the town looks better than only small snowball) but final effect will be same - target in flames :) You can make own shape of barrel, and also joint it with Movecraft, f.e. we have moveable balista, which has own .craft file, own cannon type and projectiles. It works like mobile cannon. But with the catapult it will be almost the same, just only change muzzle from the end of the barrel, and his position put on the shovel/net of catapult/trebuchet (Cannnons has also in examples something like mortar ... so you can use it and rebuild shape to your catapult.)

**Comment by pistols12** [comment]
So you are saying just make my cannons barrels to have to look like the
crafts im trying to make via craft files, then make a craft file more or
less that acomodates each individual barrel build?

**Comment by mwkaicz** [comment]
I'm not sure, how do you think it now.

By me, you have two options:
1) build a craft, which looks like catapult which you want to move, when do you have it, save it via WE for Cannons shape,  then specify params of cannon type, make a .craft file which more or less strictly rules of allowedBlocks count and now you have moveable machine, which can fire what you want and has more or less rules of construction. 

2) it's almost same, like previous, but catapult will be a subcraft of something else, which will have strict rules on some concrete block in subcraft flyBlocks list (f.e: in classic barrels we have coal block) - this will limit count of catapults on the main craft board. You can also use some little-used block type on catapult and then put in to forbiddenBlocks on crafts, where you can deny catapults.
