### ISSUE TITLE
Ships move very slowly

### ISSUE THREAD

**Issue by Miclebrick** [msummers123/Movecraft-3#213]
On my server even with nobody else on with only empty void chunks loaded, my ship moves very slowly. It's 1300 blocks, the block queue thing is set to 2000, and the speed in the craft file is 10, but it still barely moves a few blocks per second. When other players are on it slows to a crawl. Is there a way to speed it up?

**Comment by msummers123** [comment]
Yes, the best option is to use a relatively low cruisespeed, and a relatively high cruiseskipblocks. On our server, we use cruisespeed of 0.5, and cruiseskipblocks of 4, for a total speed of 2.5 bps. We have actual speed set to 1.0 for slightly better manuevring at the dock, but still lower than cruising speed.

Your ship is fairly small, you could probably go higher. Perhaps cruisespeed of 1.0 and cruiseskipblocks of 5.

It all depends on your ship size, how many players you have, how many ships at once, and your servers single thread processor performance (multi procs DO NOT help with Minecraft). 

I definitely recommend against setting any speed for a ship larger than 100-200 blocks above 2.0. Don't set high speeds for large ships, use cruiseskipblocks instead. Also, this encourages realistic movement. Ships should go faster straight ahead (the cruise mechanic) than they do maneuvring in dock. Take a look at the included .craft files for reference.
