### ISSUE TITLE
Feature Suggestion: Engine Blocks

### ISSUE THREAD

**Issue by Mouse1703** [msummers123/Movecraft-3#217]
Engine blocks would be a list within a .craft file much like flyblocks currently is, but would be optional rather than required. A craft must contain between the minimum and maximum amount of engine blocks in order to be piloted, but if a craft's amount of engine blocks drops below the minimum while piloted, rather than sinking, the craft merely becomes unmovable, or perhaps only movable straight downward, just like if it had run out of fuel. This would allow more realistic consequences for destroying a ship's engine blocks on servers where ships are required to have quasi-realistic engines.

Also, could there perhaps be a renaming of flyblocks to a more general term? It could be confusing for "flyblocks" to be required on a car or naval ship.

**Comment by cccm5** [comment]
These actually were recently implemented

**Comment by Mouse1703** [comment]
I was not aware. How recently was it implemented? Is there an example of the syntax for this option somewhere?

**Comment by cccm5** [comment]
It was implemented on august 16th, as moveblocks. Sadly, I have no idea what the syntax is for them, but would guess that it's the same as flyblocks but with moveblocks instead of flyblocks.

**Comment by msummers123** [comment]
Yeah, the new version will have updated craft types showing the syntax. Until then, you can look at the types here:
https://dl.dropboxusercontent.com/u/11164014/MovecraftTypes.zip
The airship type has the moveblocks defined.
