### ISSUE TITLE
[ERROR] Getting errors all the time

### ISSUE THREAD

**Issue by LeaveMarim** [msummers123/Movecraft-3#227]
[2016-10-20-17.log.gz](https://github.com/msummers123/Movecraft-3/files/542862/2016-10-20-17.log.gz)

**Comment by msummers123** [comment]
Sorry for the delay, work has been crazy. I can see you have a few issues here. Your Man o War craft file has some tabs in it, YAML doesn't like tabs, so you need to remove that before it will work. 

Your other problem is it seems it did not correctly detect that you were running 1.10. It is supposed to auto detect you aren't on the right version and turn compatibility mode off. I'll take a look at that code. For now, you can turn compatibility mode off in your config.yml file and that may fix it.

**Comment by keough99** [comment]
#208

**Comment by msummers123** [comment]
This is now fixed in the version of the plugin on the spigotmc page, here is the link:
https://www.spigotmc.org/resources/movecraft.31321/
