### ISSUE TITLE
Siege Configuration questions.   Armor Block Question.

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#236]
I was wondering How to setup the Siege aspect for Movecraft. I have the Pastebin from Bacca Yarrows Video on the whole Siege aspect, but nowhere in the video does he describe HOW to setup the Siege, as in, where to put the information from his pastebin. I would Gladly make a video if someone tells me a bit about the setup/ configuration for Siege.

Also, for armor blocks, do you guys somehow increase the normal blast resistance of blocks? or do you just use unaltered endstone?

**Comment by keough99** [comment]
It's in the config files of the newer versions of movecraft if you have not regenerated your config after getting the newer versions of movecraft I suggest you regenerate your config, for siege I don't really know
