### ISSUE TITLE
Crash Report, had one, here is the whole file.  Any insight would be lovely.

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#262]
[crash-2017-07-06_05.07.00-server.txt](https://github.com/msummers123/Movecraft-3/files/1133481/crash-2017-07-06_05.07.00-server.txt)

**Comment by pistols12** [comment]
here is the entire Crash file log above.  Server is fine today, no repeat error, just wanting to find out why this happened, and looking for a little help in deciphering these files for where the real meat of the issue is explained.

Thanks!  
- CaptaingibbonsSR   ORC founder, Owner of Total war, a movecraft server set an alternate version of the 1650's.

**Comment by cccm5** [comment]
Well that's strange, could you give some more information about what was happening when this occurred?

**Comment by pistols12** [comment]
Honestly, I have no clue. It didn't happen while I was awake or on the
server. I didn't hear about it, I just found this craft file when I was
doing some other server maintenance.

**Comment by pistols12** [comment]
Crash file, not craft. LOL

**Comment by pistols12** [comment]
it never happened again. Closed.
