### ISSUE TITLE
*SIEGE CONFIGURATION*  Assistance needed.

### ISSUE THREAD

**Issue by pistols12** [msummers123/Movecraft-3#265]
Hey all, so as you all know, there is VERY little, to know information posted on how to configure siege, where to even put the YML file, and so on. After some testing, I got the drop box file from a bacca video on siege demonstration, here is that file:

https://dl.dropboxusercontent.com/u/11164014/sieges.yml

At any rate, I am having issues using this config, and getting my regions to work in place of the example ones.  Here is what I tried to do:

sieges:
    'cancun':
        SiegeRegion: 'cancun'
        CraftsToWin:
            - 'Airship'
            - 'SubAirship'
            - 'BigAirship'
            - 'BigSubAirship'
        CostToSiege: 2000000
        DoubleCostPerOwnedSiegeRegion: true
        DailyIncome: 200000
        ScheduleStart: 1600 # military time
        ScheduleEnd: 1700 # military time
        RegionToControl: 'aerieontheisleairspace'
        DelayBeforeStart: 3600 # in seconds
        SiegeDuration: 1800 # in seconds

I have a region called cancun, I changed the names to such aside from the "RegionToControl: " item as I had the same results with Cancunairspace or that default examplem from the file.

The region I am trying to use is setup, its listed on world guard region list, its alterable in terms of flags and so on, but when I do /siege with this in the config i get "internal error"  fault.  

Any ideas?

PS.  If i get this all working I am doing a documentation on HOW to get sieges working for anyone who wants to know, so the help would be appreciated by all of movecraft users with this same issue.

**Comment by pistols12** [comment]
For the record, sieges.yml is directly in my movecraft folder.

**Comment by oh-noey** [comment]
Posting the log would be a big help

**Comment by pistols12** [comment]
Got it already, thanks though matey. I'll link my step by step video tutorial here for your guys.
