### ISSUE TITLE
Movecraft 1.14 -  cruise sign and stick not working 

### ISSUE THREAD

**Issue by otsmania** [msummers123/Movecraft-3#286]
i downloaded movecraft 7.0 for minecraft 1.14 " https://github.com/eirikh1996/Movecraft/releases "
the pilot sign works for every .craft, but the cruise sign and the stick dont.
i already set the pilot tool to 280.
  And i also got this: "No fuel types specified in config. Registering default fuel types charcoal with burning time 7.0, coal with burning time 7.0, coal_block with burning time 79.0,"
but i can't find fuel in the config file.

**Comment by otsmania** [comment]
Also commands like /pilot and /cruise works

**Comment by mwkaicz** [comment]
Hi @ostmania,
fuelBurnRate must be set in the .craft file. See https://github.com/msummers123/Movecraft-3/blob/5e8938fcd0125294b965abd255178f88fe9e5169/src/main/resources/types/BigAirship.craft 
But as I know, there is no place in config, where you can set specific type of fuel: https://github.com/msummers123/Movecraft-3/search?p=1&q=fuel&unscoped_q=fuel
It looks like it's only information notice. But in the code I don't see any row, where is loaded some fuel type.
cruise must be allowed in the same .craft file:  `canCruise: true` ... there is not too much reasons, why sign doesn't work and /cruise command does ... it looks like it should be a conflict with another plugin. Try to remove some of them.

**Comment by otsmania** [comment]
i'm using the latest spigot version with build tools

**Comment by otsmania** [comment]
So i changed the pilot tool to STICK and it works, only thing to fix now is the Cruise sign that i cant use

**Comment by otsmania** [comment]
@mwkaicz It worked!!, i change some things in the config file and now it works prorpertly, it was the pilot tool that was set to 280, and i changed to STICK and now even the Cruise sign works,
but i have a question yet. How i enable my ship to move entities like villagers or sheeps?

**Comment by mwkaicz** [comment]
@otsmania as I know, this is not possible at this moment. Only dropped items and players are moved with the craft. Try to add new request for it.

**Comment by otsmania** [comment]
thx!!!!
