### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by mwkaicz** [msummers123/Movecraft-3#64]
please update EN localisation file (maybe should be good to update getLocalization page too but I'm not sure if you have access to Alexs account of Movecraft) , there are missing some phrases (f.e: warning before merging of the craft)

EDIT: there are missing subcraft rotation info and man over board info too

**Comment by msummers123** [comment]
Sorry this took so long, but it is now fixed. I *think* I have all of them. I will post the new version soon
