### ISSUE TITLE
Future Feature: "Tracers" for cannon fire

### ISSUE THREAD

**Issue by Baccayarro** [msummers123/Movecraft-3#69]
Currently you can not see TNT projectiles or explosions further than about 50 blocks away. This makes it difficult to aim further than that. As cannons become more and more powerful, this is becoming a larger and larger problem. 

One possible solution I have thought of is to have the plugin add a flaming arrow whenever it detects a TNT entity being pushed by an explosion (IE: a cannon firing). The flaming arrow would have as close to the trajectory of the TNT as possible, allowing players to visibly see the arc of the cannons.

**Comment by mwkaicz** [comment]
I know, that this is done, but check this: https://www.youtube.com/watch?v=RNegSEY_QrU&list=TLyUWKOaxWDGo

**Comment by msummers123** [comment]
It's wierd, when I tested particles they were not visible at the distances he shows. Maybe only certain particles are?

**Comment by mwkaicz** [comment]
I haven't time to test it now, but there must be some option how he made it. I'll try to look on it at the weekend.
