### ISSUE TITLE
checking for building ability not just through worldguard?

### ISSUE THREAD

**Issue by chillerkraft** [msummers123/Movecraft-3#72]
im having a hell of a time finding a sufficient skyblock plugin that uses worldguard regions to disallow movecrafts moving out of players island spaces. is there any way movecraft could check for build permissions not just from worldguard but from actual abilities to build?? id think thered be another way for a plugin to check for build perms not just through worldguard,
id prefer skyblock regions, but they can get laggy and its hard to find so, i think id be happy enough with movecraft checking for more then just worldguard build flag perms

**Comment by chillerkraft** [comment]
considoring moving on to 1.8 soon, might like to hear some advice from you and maybe get some help from you aswell

**Comment by TylerS1066** [comment]
I can help if you need

**Comment by chillerkraft** [comment]
where can u help me

**Comment by TylerS1066** [comment]
I've had to make the switch to 1.8 on my server so I can help you with links to 1.8 versions of alot of popular plugins

**Comment by chillerkraft** [comment]
well, i heard theres no essentials for 1.8 right?
im using ultimate core at the moment, do you know any of my other options? its all i can find

**Comment by chillerkraft** [comment]
do u know of any way for server owners to create custom portals on there server that other players can build and use them on there own, just like nether and end portals?
i want to make an overworld portal for players to build and get to the overworld
i also want to replace vanilla nether portals, so that people can get to the nether on there own with there own built portals without having new portals getting created in the nether world.
it's gonna be in my skyblock world, so i alsocant have people entering nether portals in the nether and recreating broken ones in other peoples skyblocks
but all of this i believe would make a next epic plugin. i dont think it's been made yet.
can you or someone reading this help me get this plugin made?
i made a post here
http://bukkit.org/threads/custom-buildable-portals.333206/

**Comment by TylerS1066** [comment]
Back in the dark ages of my server (when I was scared of anything that said configuration and had a Admin running lose) I used a plugin that created portals using wool, I don't know if this plugin works on 1.8 but it did what you are describing as player made portals

Link to plugin:
http://dev.bukkit.org/bukkit-plugins/color-portals/

**Comment by chillerkraft** [comment]
i can try that for now,
but do u agree my idea for a plugin is epic and very useful and beautiful?
servers could let there player make there very own server unique portals!
ughh i cant get over how awesome this idea is..
it seems very easily doable, and it seems like its not done yet,
and it seems like sooo many people would looove this plugin
fjdslfslksjlkf :P

**Comment by TylerS1066** [comment]
I think that it is a good idea, try searching around to find a more up to date plugin, the one I told you about hasn't been updated sinced Mar 24, 2013

**Comment by chillerkraft** [comment]
there a multiverse for 1.8?

**Comment by chillerkraft** [comment]
im having problems with using the latest movecraft on the latest spigot,
for once, it's asking me for fuel,
when i put a furnace with coal onto my craft,
it still says i need fuel
then i get an error msg
do you know why this is happening?

http://pastebin.com/hZCySqv1

**Comment by msummers123** [comment]
I'll take a look at this as soon as I can, but this week is crazy busy for me, so it might not be for a few days. Sorry!

**Comment by chillerkraft** [comment]
im using worldguard latest, and spigot latest, is there anything u know that is causing this problem? i can make changes, i just quickly threw some plugins together to check compatability for a new server build. but yea if u dont know then thats fine i just thought maybe its an obvious fix

**Comment by TylerS1066** [comment]
Use these plugins:

WorldGuard
http://builds.enginehub.org/job/worldguard/6524/download/worldguard-6.0.0-SNAPSHOT.zip
Worldedit:
http://builds.enginehub.org/job/worldedit/6519/download/worldedit-bukkit-6.0.1-SNAPSHOT-dist.jar
P

Multiverse's newest BukkitDev build works and the error you are getting is from Movecraft, try updating if you haven't already

**Comment by chillerkraft** [comment]
im thinking the error i got from multiverse had to do with my server monsters set to false but multiverse set to true, but i could be wrong. ill put mvcore back on and see what happens this time n notbelazy/setmonstersoffinboth

**Comment by chillerkraft** [comment]
nvm im gonna just turn monsters off in mv, or wg regions

**Comment by chillerkraft** [comment]
and ill try those wg and we builds aswell

**Comment by chillerkraft** [comment]
im getting an error message when i place a sign

**Comment by chillerkraft** [comment]
also, should i turn off compatability mode?

**Comment by chillerkraft** [comment]
ouu i think i fixed the sign problem by finally adding the movecraft types files

**Comment by chillerkraft** [comment]
really wierd problem now, i cant see to go upwards past a certain point, i believe its the height i created the craft at. i can go downwards, and back up to that heigh, but not higher :S i get no error msgs at all

**Comment by chillerkraft** [comment]
every time i try to go upwards from that height, i go up 1, then down 1, and so on. over and over again

**Comment by chillerkraft** [comment]
okay , another testing update... i can go upwards in some place, but then when i go to the places i wasnt able to go upwards, it forces me downwards when i move

**Comment by msummers123** [comment]
You are probably witnissing the maxheightaboveground behavior. You may want to see the latest video about movecraft updates to understand what this does and how it works. In short, you can (and probably should) limit how high people can fly above the terrain. This reduces lag significantly. If you are not concerned about lag, you can remove the maxheightaboveground attribute from your .craft file.

**Comment by chillerkraft** [comment]
im using this plugin in an empty space world (Skyblock)

**Comment by chillerkraft** [comment]
i notice in ur video, when u move, it doesnt cause ur viewpoint to glitch around, do u know what i mean? i get this all the time, when im moving i cant look around until 2 seconds after not moving anymore, or else itll point me back to where i was looking where i was looking before the ship was about to make its next move.. can this be fixed?

**Comment by chillerkraft** [comment]
im thinking i should scrap my plans for using movecraft in skyblock

**Comment by TylerS1066** [comment]
The issue is probably because there is no ground for you to fly over and this is glitching the system

**Comment by chillerkraft** [comment]
so no movecraft in spaceworlds anymore?

**Comment by msummers123** [comment]
Oh, no, just disable it. Don't set MaxHeightAboveGround. Or if you are using an existing .craft, remove it from the .craft file.

On the viewport jerkyness thing, I would highly recommend having a "cruiseSpeed" setting on any craft that will cruise and having it as low as possible. Preferably less than 1. I use 0.5. Then compensate with a high cruiseSkipBlocks. That will lessen (but not eliminate) the jerkyness.

**Comment by msummers123** [comment]
Any luck with this? I would like to close this ticket.

**Comment by chillerkraft** [comment]
id rather just have a plugin where i can make crafts not battle ships, and this plugin is too laggy and problematic for me. not using it anymore
