### ISSUE TITLE
[REQUEST] Ship teleport/home command

### ISSUE THREAD

**Issue by DrakeEldridge** [msummers123/Movecraft-3#74]
I was wondering if movecraft could get a command that teleports the ships owner back to their ship. The /manoverboard command teleports to last ship they were on, this is good but what if the last ship user was on wasn't their own ship. This command would tp the player to their ship no matter where it is. Perhaps using a sign, player places a sign down with "ship - Owner - (name) or something, and it saves the location of the sign and you can teleport to it, then if the ship is moved, the sign moves with the ship like the other signs, and if you use /shipteleport or something it, moves you to the sign (aka your ship) 

One was I can think of this working is when you place owner sign, the sign logs the co-ords 1 block next to it and sets it as /sethome ship (players name) maybe that would work, and when the ship moves and stops, the plugins runs it again and saves the new coords next to the sign and runs the /sethome ship (player name) overwriting the old home. so where ever ship moves, home is set to next to the sign. and the /shipteleport command just runs /home ship (playername) Not sure if this would work. But would be really useful. Thanks.

-Drake

**Comment by TylerS1066** [comment]
I believe a system like this has been brought up before, the issue with this is that to have this you would end up logging the co-ords and world of every ship, something the plugin doesn't do right now and would probably take msummers alot of time

**Comment by DrakeEldridge** [comment]
It logs the "crates" that are placed on ships doesnt it? The crate is tracked as the ship moves? So couldnt it track a "home" sign if the ship owner places one? So it doesnt track all ships, just the ones with a home sign?

**Comment by msummers123** [comment]
Right, but I'm afraid that's precisely why the crate system has problems, and is unsupported, and why I don't want to repeat it with another file backed system.

That being said, I might just use Essentials for that, if I can figure out how to hook into it. Let it figure out how to deal with the backend, just set the home through the plugin.

**Comment by msummers123** [comment]
This has been implemented with Crew: signs setting your spawn point

**Comment by mwkaicz** [comment]
This stop working with Essentials when player use /sethome. I'll fix it during this week.

**Comment by DrakeEldridge** [comment]
Thanks for adding this feature :D 
Quick question, is there away to stop others from driving/stealing airship owned by a crew or player?

**Comment by mwkaicz** [comment]
As I know, at this time this option isn't there.

I'm not sure at this moment, but you can do it yourself: 

to reset essentials home, you must find your userdata file in ```plugins/Essentials/userdata/```  folder and remove rows related with homes

then ```/essentials/reload```   
... go to the ship and use bed ... then die, when you will have ```respawn-at-home: true``` in essentials config, you should respawn in the ship.

**Comment by DrakeEldridge** [comment]
I will give it a test later today. So is players do /spawn, the should go to spawn. and if they die, they should go to their bed. Sounds good. I have the plugin "bedhome" that adds /bed command. So players can teleport to their bed. I can change the command to be /ship or something and then players should be able to tp to their beds on their ship at any time.
