### ISSUE TITLE
Players become invisible on moving ship

### ISSUE THREAD

**Issue by Zoagel** [msummers123/Movecraft-3#84]
Players become invisible when the ship moves.

VIDEO (issue reproduction) https://www.youtube.com/watch?v=MDm0Lz4B8TA

I've tried removing all other plugins, that didn't seem to affect it. Console looks clean.
This might be a Vanilla or config issue, but im not sure.

There's not a fixed trigger to turn the invisibility off, as far as i know, just walk and jump around and it will be gone after a few seconds.

Yet, its very annoying in close combat PvP. You will not lose your invisibility if you attack someone, and players cant target you.

Im running Craftbukkit 1.8.1, from the Buildtools from 27/12/2014, and the latest latest version of Movecraft from http://www.planetminecraft.com/mod/movecraft-reloaded---loraxe42s-fork/ (3 days ago). Also tried it with the latest version of Movecraft on Bukkit (http://dev.bukkit.org/bukkit-plugins/movecraft/files/24-movecraft-v-3-1-x67-for-1-8/), same problem.

(compatibilitymode was on by default)

**Comment by msummers123** [comment]
Yeah, this is actually a known spigot bug, where it does not update the other clients when an entity teleports. Only the client that is actually teleported is updated. This doesn't happen in vanilla Minecraft.

If Spigot doesn't fix it, I may add a workaround, but for now I will hope they fix it on their end.

**Comment by Pocketkid2** [comment]
Oh, the spigot bugs...

**Comment by msummers123** [comment]
Yeah, we should all ask for our money back!

Oh... wait... :)

**Comment by msummers123** [comment]
Spigot seems to have fixed this on their end.
