### ISSUE TITLE
Issue with large watercraft movement

### ISSUE THREAD

**Issue by MRGhorm1379** [msummers123/Movecraft-3#85]
While moving a very large watercraft, sometimes the craft will pick up random blocks of air for no apparent reason. These blocks of air act just as a part of the ship would, you can hover inside these blocks of air and be considered inside the ship, control the ship from inside these blocks of air, and most importantly, these blocks of air collide with terrain, making movement in tight spaces near impossible. These blocks of air are almost always at or just below water level, and can be up to 60 blocks off of the front or back, but never more than a few off of the sides. Even after releasing the craft and piloting it again, these blocks of air still seem to be attached to the ship. I have no idea how they get there, and they're not attached to anything connected to the ship.

Bukkit version 1.7.9 R0.2 (MC 1.7.10), Movecraft 3.1.X67, WorldGuard 6.0.0-beta-02

Image of the pocket of air with ship in the background.
![2015-02-01_15 34 22](https://cloud.githubusercontent.com/assets/8388386/5994243/bd1633c2-aa28-11e4-901c-fe1e2b839323.png)

**Comment by msummers123** [comment]
That is bizarre. Could you get me a schem or something to test this?

**Comment by msummers123** [comment]
perhaps the .craft file too

**Comment by MRGhorm1379** [comment]
I'm not quite sure about getting you a schem, I can tell you however that the ship in and of itself is about 6300 blocks large. Exterior is completely wood, Stone slabs for cannons, wool for strings and sails, some torches here and there, 3 furnaces and anvils, one or two crates, nothing that seems too out-of-the-ordinary. I can give you a detailed list of every single block currently aboard the ship if you'd like.
However, here's everything that's in the craft file:

name: Lineship
maxSize: 9000
minSize: 5
allowedBlocks: 
    - 5
    - 10
    - 11
    - 17
    - 20
    - 23
    - 25
    - 26
    - 29
    - 33
    - 34
    - 35
    - 41
    - 42
    - 43
    - 44
    - 47
    - 49
    - 50
    - 53
    - 54
    - 55
    - 57
    - 58
    - 61
    - 62
    - 63
    - 64
    - 65
    - 68
    - 69
    - 70
    - 71
    - 72
    - 75
    - 76
    - 77
    - 82
    - 85
    - 87
    - 89
    - 92
    - 93
    - 94
    - 95
    - 96
    - 98
    - 101
    - 102
    - 107
    - 109
    - 112
    - 113
    - 114
    - 116
    - 117
    - 118
    - 122
    - 123
    - 124
    - 125
    - 126
    - 130
    - 131
    - 133
    - 134
    - 135
    - 136
    - 138
    - 139
    - 140
    - 143
    - 144
    - 145
    - 146
    - 147
    - 148
    - 149
    - 150
    - 151
    - 152
    - 154
    - 155
    - 156
    - 157
    - 158
    - 159
    - 171
    - 172
    - 173

forbiddenBlocks:
    - 7

canCruise: true
canDirectControl: true
canStaticMove: true
cruiseSkipBlocks: 4
canFly: false
sinkPercent: 51.0
minHeightLimit: 40
maxHeightLimit: 250
useGravity: true
allowHorizontalMovement: true
allowVerticalMovement: false
speed: 1.0
tryNudge: false
flyblocks:
    5:
      - 10.0
      - 100.0

**Comment by msummers123** [comment]
Any extended pistons anywhere on the ship? Retracted pistons are ok, but extended pistons create wierd phantom blocks while moving.

**Comment by MRGhorm1379** [comment]
There are no pistons on the ship anywhere.
Although, if it's worth anything, there are lots of slabs on the sides and front of the ship. There are no slabs below the waterline though. There are stairs well underneath the waterline, but in the center of the ship. There are two sets of ladders which extend down the sides of the ship on either side, which come all the way down to the waterline. On the ship, there are also fences (both wooden and cobblestone), and wooden fence gates. Some of these are near the very back, and close to the waterline.
Also, there quite a few blocks of wool which are connected by their corners, instead of one side of a block touching another. I didn't think anything of it at the time, but these are working just fine, whereas a flag on top did not, and it was the same scenario. I don't know if that would have anything to do with the ghost blocks, but I thought I might mention it as another weird thing which could potentially contribute to them.

**Comment by TylerS1066** [comment]
Slabs, stairs, ladders, fences, and fence gates all work with Movecraft, this is probably a issue with the Movecraft engine.
That said the Movecraft engine is designed for long and narrow things explaining why the bubbles are close to the sides but can be far from the front/back.
Other than that I don't know what is happening, I've had holes in a ship that are air bubbles but never outside it.

**Comment by msummers123** [comment]
This should be fixed in the latest version
