### ISSUE TITLE
MoveCraft portcullis RMove crash

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#90]
When I click a valid RMove sign for a controlled portcullis, this crash happens and nothing is showed in the game.

http://pastebin.com/3fqnVY1t

**Comment by msummers123** [comment]
It would appear that this is caused by having a space after the comma and before the second number. Apparently it is pretty picky. There should not be any spaces in the coordinates on the sign.

**Comment by msummers123** [comment]
I would like to close this, did you have any further questions?
