### ISSUE TITLE
Crash when right clicking airship sign

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#94]
http://pastebin.com/CeJ0sLdS

**Comment by msummers123** [comment]
Yeah, you have a corrupt crate inventory file. Crates have a lot of problems with them, which is why they are now a legacy feature. I would recommend disabling them in your config.yml. Use chests instead.

**Comment by msummers123** [comment]
Just realized you posted this before. So... did disabling crates not fix it?

**Comment by Pocketkid2** [comment]
Thanks!
