### ISSUE TITLE
Glowstone and other lighting not traveling with the ship

### ISSUE THREAD

**Issue by Pocketkid2** [msummers123/Movecraft-3#95]
In the latest version for 1.8, I have noticed that lighting from blocks in the ship (I have seen this with glowstone AND redstone lamps) do not follow the ship. YOU have to stop and manually update the blocks for the light to come back. This is annoying when trying to fly in the dark.

**Comment by msummers123** [comment]
Do you have compatibility mode on?

**Comment by Pocketkid2** [comment]
No, it is currently set to false. Is that the problem?

**Comment by mwkaicz** [comment]
yes, turn it on, it will solve your problem

**Comment by Pocketkid2** [comment]
Okay, that works. Although it seems as though it does not work for moving vertically...
