### ISSUE TITLE
Hopper caused crash

### ISSUE THREAD

**Issue by Uskaanax** [msummers123/Movecraft-3#99]
I had built an AirShip and thought I would be smart by making the furnace refill automatically. I had a hopper on the side of the furnace, newly connected since the original 'flight' and hooked to the furnace. Charcoal was in the hopper and a chest on top of it filled with more charcoal. Upon the first test flight in this configuration, the server crashed out and would not start. The hopper's location is noted below so I went in with mcedit and removed the hopper. Upon restart, without the hopper, everything was OK. I've tested on a smaller, non-production server with only movecraft and verified that this error is a result of Movecraft and the way it requires a furnace/charcoal, but the way it interacts with the server on ticks is causing an issue.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[14:44:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R1.ReportedException: Ticking block entity
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:719) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R1.TileEntity.getOwner(TileEntity.java:190) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.TileEntityHopper.r(TileEntityHopper.java:262) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.TileEntityHopper.m(TileEntityHopper.java:188) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.TileEntityHopper.c(TileEntityHopper.java:176) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1267) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715) ~[craftbukkit-1.8.jar:git-Bukkit-33d5de3]
        ... 4 more
[14:44:51] [Server thread/ERROR]: This crash report has been saved to: /opt/minecraft/spigot/./crash-reports/crash-2015-03-01_14.44.51-server.txt
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/1/15 2:44 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at net.minecraft.server.v1_8_R1.TileEntity.getOwner(TileEntity.java:190)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.r(TileEntityHopper.java:262)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.m(TileEntityHopper.java:188)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.c(TileEntityHopper.java:176)
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1267)
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539)
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.server.v1_8_R1.TileEntity.getOwner(TileEntity.java:190)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.r(TileEntityHopper.java:262)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.m(TileEntityHopper.java:188)
        at net.minecraft.server.v1_8_R1.TileEntityHopper.c(TileEntityHopper.java:176)

-- Block entity being ticked --
Details:
        Name: Hopper // net.minecraft.server.v1_8_R1.TileEntityHopper
        Block type: ID #154 (tile.hopper // net.minecraft.server.v1_8_R1.BlockHopper)
        Block data value: 2 / 0x2 / 0b0010
        Block location: World: (-19,71,399), Chunk: (at 13,4,15 in -2,24; contains blocks -32,0,384 to -17,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Actual block type: ID #154 (tile.hopper // net.minecraft.server.v1_8_R1.BlockHopper)
        Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
        at net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1267)
        at net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539)

-- Affected level --
Details:
        Level name: RPGServer
        All players: 1 total; [EntityPlayer['Uskaanax'/736, l='RPGServer', x=-30.59, y=75.00, z=404.61](Uskaanax at -30.588000769935906,75.0,404.608805630015)]
        Chunk stats: ServerChunkCache: 855 Drop: 0
        Level seed: 6613237594970218663
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: 200.00,72.00,235.00 - World: (200,72,235), Chunk: (at 8,4,11 in 12,14; contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
        Level time: 568263305 game time, 574869884 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 57527 (now: false), thunder time: 92991 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715)
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.8
        Operating System: Linux (amd64) version 3.13.0-32-generic
        Java Version: 1.7.0_75, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 6732496880 bytes (6420 MB) / 8232894464 bytes (7851 MB) up to 11453595648 bytes (10923 MB)
        JVM Flags: 2 total; -Xms8G -Xmx12G
        IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
        CraftBukkit Information:
   Running: CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT) true
   Plugins: { WarpPortals v5.6.3 com.mccraftaholics.warpportals.bukkit.PortalPlugin [], MiningMachine v0.7.5 com.pluggertech.miningmachine.MiningMachine [Tanner Embry], DeathChest v2.5 me.CMG.DeathChest.DeathChest [], Movecraft v3.1.X73 net.countercraft.movecraft.Movecraft [BaccaYarro], DakadoBoats v1.5 vip.production.dakado.boats.Boats [Dakado], BiomeTP v2.3 org.thespherret.plugins.biometp.Start [Spherret.], DeathCount v1.0 com.caved_in.DeathCount [], YAPP v1.4 com.nisovin.yapp.YAPP [nisovin], AutoSaveWorld v4.13 autosaveworld.core.AutoSaveWorld [_Shevchik_], MyHome v2.3.1 me.taylorkelly.myhome.MyHome [spathizilla], AntiMobSpawn v4.0 uk.samlex.ams.AntiMobSpawn [Sam_lex], TreeAssist v5.8.89 me.itsatacoshop247.TreeAssist.TreeAssist [itsatacoshop247], dynmap v2.1-SNAPSHOT-1091 org.dynmap.bukkit.DynmapPlugin [mikeprimm],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:272), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read(BufferedInputStream.java:254), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261), org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145), org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2349), net.minecraft.server.v1_8_R1.ThreadCommandReader.run(ThreadCommandReader.java:33)], WAITING Thread-5: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_8_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:25), java.lang.Thread.run(Thread.java:745)], WAITING Dynmap Render Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1085), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Server Watchdog: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R1.ThreadWatchdog.run(SourceFile:73), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Chunk I/O Executor Thread-1: [java.util.zip.Inflater.inflateBytes(Native Method), java.util.zip.Inflater.inflate(Inflater.java:259), java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152), java.io.BufferedInputStream.fill(BufferedInputStream.java:235), java.io.BufferedInputStream.read1(BufferedInputStream.java:275), java.io.BufferedInputStream.read(BufferedInputStream.java:334), java.io.DataInputStream.readFully(DataInputStream.java:195), java.io.DataInputStream.readFully(DataInputStream.java:169), net.minecraft.server.v1_8_R1.NBTTagByteArray.load(SourceFile:29), net.minecraft.server.v1_8_R1.NBTTagCompound.a(SourceFile:380), net.minecraft.server.v1_8_R1.NBTTagCompound.load(SourceFile:48), net.minecraft.server.v1_8_R1.NBTTagList.load(SourceFile:50), net.minecraft.server.v1_8_R1.NBTTagCompound.a(SourceFile:380), net.minecraft.server.v1_8_R1.NBTTagCompound.load(SourceFile:48), net.minecraft.server.v1_8_R1.NBTTagCompound.a(SourceFile:380), net.minecraft.server.v1_8_R1.NBTTagCompound.load(SourceFile:48), net.minecraft.server.v1_8_R1.NBTCompressedStreamTools.a(SourceFile:106), net.minecraft.server.v1_8_R1.NBTCompressedStreamTools.a(SourceFile:71), net.minecraft.server.v1_8_R1.NBTCompressedStreamTools.a(SourceFile:67), net.minecraft.server.v1_8_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:82), org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:19), org.bukkit.craftbukkit.v1_8_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1), org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor$Task.init(AsynchronousExecutor.java:150), org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor$Task.initAsync(AsynchronousExecutor.java:95), org.bukkit.craftbukkit.v1_8_R1.util.AsynchronousExecutor$Task.run(AsynchronousExecutor.java:85), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING AutoSaveWorld AutoSaveThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.save.AutoSaveThread.run(AutoSaveThread.java:82)], WAITING Ebean-AntiMobSpawn.0: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), com.avaje.ebeaninternal.server.lib.thread.PooledThread.run(PooledThread.java:75), java.lang.Thread.run(Thread.java:745)], RUNNABLE Netty Server IO #3: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:618), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], RUNNABLE Netty Server IO #0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:618), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING AutoSaveWorld CrashRestartThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.restart.CrashRestartThread.run(CrashRestartThread.java:98)], TIMED_WAITING AutoSaveWorld WorldRegenCopyThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.worldregen.WorldRegenCopyThread.run(WorldRegenCopyThread.java:82)], RUNNABLE pool-5-thread-1 Selector0: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), org.dynmap.jetty.io.nio.SelectorManager$SelectSet.doSelect(SelectorManager.java:569), org.dynmap.jetty.io.nio.SelectorManager$1.run(SelectorManager.java:290), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.v1_8_R1.ThreadSleepForever.run(SourceFile:64)], RUNNABLE Netty Server IO #2: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:618), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], WAITING Dynmap Render Thread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftFuture.get(CraftFuture.java:54), org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftFuture.get(CraftFuture.java:42), org.dynmap.MapManager$CheckWorldTimes.run(MapManager.java:804), org.dynmap.MapManager$DynmapScheduledThreadPoolExecutor$2.run(MapManager.java:206), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471), java.util.concurrent.FutureTask.run(FutureTask.java:262), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178), java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:278), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING Keep-Alive-Timer: [java.lang.Thread.sleep(Native Method), sun.net.www.http.KeepAliveCache.run(KeepAliveCache.java:172), java.lang.Thread.run(Thread.java:745)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1640), org.bukkit.craftbukkit.v1_8_R1.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.server.v1_8_R1.CrashReportSystemDetails.a(SourceFile:78), net.minecraft.server.v1_8_R1.CrashReport.h(CrashReport.java:43), net.minecraft.server.v1_8_R1.CrashReport.<init>(CrashReport.java:32), net.minecraft.server.v1_8_R1.CrashReport.a(CrashReport.java:228), net.minecraft.server.v1_8_R1.World.tickEntities(World.java:1269), net.minecraft.server.v1_8_R1.WorldServer.tickEntities(WorldServer.java:539), net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:715), net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284), net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609), net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING AutoSaveWorld AutoRestartThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.restart.AutoRestartThread.run(AutoRestartThread.java:92)], WAITING Java2D Disposer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), sun.java2d.Disposer.run(Disposer.java:145), java.lang.Thread.run(Thread.java:745)], WAITING Thread-21: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:186), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), org.dynmap.AsynchronousQueue.pop(AsynchronousQueue.java:44), org.dynmap.AsynchronousQueue.running(AsynchronousQueue.java:128), org.dynmap.AsynchronousQueue.access$000(AsynchronousQueue.java:9), org.dynmap.AsynchronousQueue$1.run(AsynchronousQueue.java:83), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING HashSessionScavenger-0: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Dynmap Render Thread: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090), java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING AutoSaveWorld AutoPurgeThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.purge.AutoPurgeThread.run(AutoPurgeThread.java:75)], RUNNABLE pool-5-thread-2 Acceptor0 SelectChannelConnector@0.0.0.0:8123: [sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method), sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:241), org.dynmap.jetty.server.nio.SelectChannelConnector.accept(SelectChannelConnector.java:109), org.dynmap.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:938), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING EbeanCacheWarmer: [java.lang.Object.wait(Native Method), java.util.TimerThread.mainLoop(Timer.java:552), java.util.TimerThread.run(Timer.java:505)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:503), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)], TIMED_WAITING EbeanBackgroundThread: [java.lang.Thread.sleep(Native Method), com.avaje.ebeaninternal.server.lib.BackgroundThread$Runner.run(BackgroundThread.java:168), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING AutoSaveWorld AutoBackupThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.backup.AutoBackupThread.run(AutoBackupThread.java:95)], TIMED_WAITING AutoSaveWorld AutoConsoleCommandThread: [java.lang.Thread.sleep(Native Method), autosaveworld.threads.consolecommand.AutoConsoleCommandThread.run(AutoConsoleCommandThread.java:95)], RUNNABLE Netty Server IO #1: [sun.nio.ch.EPollArrayWrapper.epollWait(Native Method), sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269), sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:618), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306), io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116), java.lang.Thread.run(Thread.java:745)], TIMED_WAITING process reaper: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615), java.lang.Thread.run(Thread.java:745)], RUNNABLE DestroyJavaVM: [],}
   Recent tasks from 241-271{}
        Profiler Position: N/A (disabled)
        Player Count: 1 / 20; [EntityPlayer['Uskaanax'/736, l='RPGServer', x=-30.59, y=75.00, z=404.61](Uskaanax at -30.588000769935906,75.0,404.608805630015)]
        Is Modded: Definitely; Server brand changed to 'CraftBukkit'
        Type: Dedicated Server (map_server.txt)
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[15:45:17 INFO]: This server is running CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[15:45:17 INFO]: Checking version, please wait...
[15:45:18 INFO]: You are running the latest version

**Comment by msummers123** [comment]
Ok. Yeah, I can see why that might cause problems. Unfortunately I can't think of a way around it, it's just how the minecraft code handles the hoppers. Between that, and the hoppers randomly losing items if they are active while the ship moves, perhaps hoppers should simply be disabled.

**Comment by mwkaicz** [comment]
What about stop hoppers actions during translation or replace them with something else and keep its data in craft data? I'll try to find some way, disabling blocks isn't the best. It's same like extended pistons ... but something has changed, because I know that both these blocks worked in the past.

**Comment by Uskaanax** [comment]
One of my users reported the loss of all contents from within her chests in the last couple hours. Occurred on an AirSkiff. No hopper was involved. Same server as one above that did have the problem.

**Comment by msummers123** [comment]
Ah yes, you may have seen this spigot error:
https://hub.spigotmc.org/jira/browse/SPIGOT-611
This started with spigot builds after December, and basically it affects any block with special "tile data" associated with it (signs, furnaces, etc). If you replace that block with a chest, then try to fill that chest, the chest will fail to fill. You also get an error on your server console.

The effect is the contents of the chest are lost. At this time I have a two workarounds:
1 - switch to an older build of Spigot 1.8, from December or earlier
2 - ensure chests are never adjacent to signs, furnaces, anything with an inventory or other special data in your various aircraft

If Spigot does not fix the bug, I am working on a programming change that seems promising as a solution.

**Comment by mwkaicz** [comment]
yes moving of chests is still problematic, when you put there a lot of chests and trapped chests in like chessboard schema, and then make a move, some are invisible and some looks like double chests, but these are still one part as chest and second part is trapped_chest

**Comment by msummers123** [comment]
The workaround worked, although there is still a graphical glitch. Relogging will fix it.
